name: Personal Website Heimo Paffhausen
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
collections:
  records:
    output: false
